name: CI - Dogecoin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        include:
          - arch: aarch64
            docker_arch: linux/arm64
          - arch: x86_64
            docker_arch: linux/amd64

    steps:
    - uses: actions/checkout@v2

    - name: Set tag
      id: vars
      run: echo "tag=$(cat Dockerfile | grep 'FROM bloknodes/base-nodes' | cut -d '-' -f3)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: ${{ matrix.docker_arch }}
        build-args: |
          CRYPTO_ARCH=${{ matrix.arch }}
        tags: |
          ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:${{ steps.vars.outputs.tag }}
          ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:latest
